### PR TITLE
Update precompile.yml

### PR DESCRIPTION
**Pull request by willfore**
I re-worked the precompile.yml so that it will produce a more up to date version of per-compiled binary's and will complete without issues on githubs default runners. Please give this a merge and publish a new version :)

### CODE REVIEW

**Comment by vgrechin** [comment]
Hi @willfore, I've got no write access to this repo so may not merge.
I tried the script on my Tegra linux box of arm64 platform and the issues still persists, so the update is necessary:
```elixir
#! /usr/bin/env elixir

Mix.install( [
    {:duckdbex, "~> 0.3"}
] )

IO.puts( "Success!" )
```
Error log:
```
~/workspace/elixir$ elixir duckdb.exs 
Resolving Hex dependencies...
Resolution completed in 0.252s
New:
  cc_precompiler 0.1.10
  duckdbex 0.3.1
  elixir_make 0.8.4
* Getting duckdbex (Hex package)
Request failed (:timeout)
If this happens consistently, adjust your concurrency and timeout settings:

    HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get
** (Mix.Error) Package fetch failed and no cached copy available (https://repo.hex.pm/tarballs/duckdbex-0.3.1.tar)
    (mix 1.16.2) lib/mix.ex:580: Mix.raise/2
    (hex 2.0.6) lib/hex/scm.ex:144: Hex.SCM.update/1
    (hex 2.0.6) lib/hex/scm.ex:227: Hex.SCM.checkout/1
    (mix 1.16.2) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix 1.16.2) lib/mix/dep/converger.ex:229: Mix.Dep.Converger.all/8
    (mix 1.16.2) lib/mix/dep/converger.ex:162: Mix.Dep.Converger.init_all/8
    (mix 1.16.2) lib/mix/dep/converger.ex:146: Mix.Dep.Converger.all/4
    (mix 1.16.2) lib/mix/dep/converger.ex:89: Mix.Dep.Converger.converge/4
```

**Comment by willfore** [comment]
this PR is a change to the precompile.yml file which allows the github actions to build the precompiled binaries properly using the free action builders. Once this has completed and a new package is pushed to hex containing these it should work just fine. You can check the release I produced in my fork https://github.com/willfore/duckdbex/tree/main for more reference. @AlexR2D2 should be the one that merges this PR :)

**Comment by vgrechin** [comment]
I updated the script to this
```elixir
#! /usr/bin/env elixir

Mix.install( [
    {:duckdbex, git: "https://github.com/willfore/duckdbex", tag: "v0.3.1"}
] )

IO.puts( "Success!" )
```
but still getting an error:
```
~/workspace/elixir$ elixir duckdb.exs 
* Getting duckdbex (https://github.com/willfore/duckdbex - v0.3.1)
remote: Enumerating objects: 297, done.        
remote: Counting objects: 100% (79/79), done.        
remote: Compressing objects: 100% (29/29), done.        
remote: Total 297 (delta 56), reused 49 (delta 46), pack-reused 218        
Resolving Hex dependencies...
Resolution completed in 0.066s
New:
  cc_precompiler 0.1.10
  elixir_make 0.8.4
* Getting elixir_make (Hex package)
* Getting cc_precompiler (Hex package)
==> elixir_make
Compiling 8 files (.ex)
Generated elixir_make app
==> cc_precompiler
Compiling 3 files (.ex)
Generated cc_precompiler app
==> duckdbex
Downloading precompiled NIF to /home/vgrechin/.cache/duckdbex-nif-2.15-aarch64-linux-gnu-0.3.1.tar.gz
Error happened while installing duckdbex from precompiled binary: "precompiled \"duckdbex-nif-2.15-aarch64-linux-gnu-0.3.1.tar.gz\" does not exist or cannot download: :enoent".

Attempting to compile duckdbex from source...
mkdir -p /home/vgrechin/.cache/mix/installs/elixir-1.16.2-erts-13.2.2.9/da7ff2435e9e0c68904bb99e89f16a25/_build/dev/lib/duckdbex/priv
g++ -O3 -std=c++11 -I"/opt/erlang/erts-13.2.2.9/include"  -I"c_src/"  -I"c_src/duckdb/" -DNDEBUG=1 -fPIC -fvisibility=hidden -c c_src/term.cpp -o /home/vgrechin/.cache/mix/installs/elixir-1.16.2-erts-13.2.2.9/da7ff2435e9e0c68904bb99e89f16a25/_build/dev/lib/duckdbex/priv/term.o
g++ -O3 -std=c++11 -I"/opt/erlang/erts-13.2.2.9/include"  -I"c_src/"  -I"c_src/duckdb/" -DNDEBUG=1 -fPIC -fvisibility=hidden -c c_src/nif.cpp -o /home/vgrechin/.cache/mix/installs/elixir-1.16.2-erts-13.2.2.9/da7ff2435e9e0c68904bb99e89f16a25/_build/dev/lib/duckdbex/priv/nif.o
```

**Comment by willfore** [comment]
you won't be able to use my repo to fix the issue. I didn't attempt to change the mix.exs files away from @AlexR2D2 repo as I'm not trying to replace his only help with the ability to get the pre-compiler to work. Once @AlexR2D2 merges this PR and runs it then produces a new release and hex push it will work without issue. You will need to wait for him to merge this and run the github action the first time.

**Comment by AlexR2D2** [comment]
@willfore, thanks a lot! I am in progress, just some adjusting with checksums...

**Pull request merged**
